
language: php

php:
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database pipcms_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

services:
  - mysql

script:
  - vendor/bin/phpunit
  - php travis/coverage-checker.php travis/clover.xml 5
  - mkdir -p build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls -v